server:
    port: 8066
logging:
    level:
        root: INFO
        org.springframework: INFO
        com.example: DEBUG
    path: src/main/resources/logs
    layout:
        pattern: "%d{yyyy-MM-dd HH:mm:ss} [%t] %-5p %c{1}:%L - %m%n"

log4j2:
    appends:
        - type: Console
          name: ConsoleAppender
          target: SYSTEM_OUT
          layout:
            type: PatternLayout
            pattern: "%d{yyyy-MM-dd HH:mm:ss} [%t] %-5p %c{1}:%L - %m%n"
        - type: File
          name: FileAppender
          path: src/main/resources/logs/app.log
          layout:
            type: PatternLayout
            pattern: "%d{yyyy-MM-dd HH:mm:ss} [%t] %-5p %c{1}:%L - %m%n"
    loggers:
        - name: org.springframework
          level: INFO
          additivity: false
          appender-ref:
            - ref: ConsoleAppender
            - ref: FileAppender
        - name: com.example
          level: DEBUG
          additivity: false
          appender-ref:
            - ref: ConsoleAppender
            - ref: FileAppender
        - name: root
          level: INFO
          additivity: false
          appender-ref:
            - ref: ConsoleAppender
            - ref: FileAppender

application:
    scheduler:
        cron: 0 0/1 * 1/1 * ? *
    sftp:
        host: ${HOST}
        port: 22
        user: ${USERNAME}
        password: ${PASSWORD}
        remote-directory: /C:/Users/Administrator/Documents
        local-directory: src/main/resources/data.txt